# Generated by Django 6.0.5 on 2026-05-14 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('medium', models.CharField(max_length=100)),
                ('style', models.CharField(max_length=100)),
                ('starting_bid_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('listing_date', models.DateTimeField(auto_now_add=True)),
                ('dimensions', models.CharField(max_length=50)),
                ('year_of_creation', models.IntegerField()),
                ('edition', models.CharField(max_length=100)),
                ('provenance', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='artworks/thumbs/')),
                ('sold_status', models.CharField(choices=[('Available', 'Available'), ('Bidding', 'Bidding'), ('Sold', 'Sold'), ('Expired', 'Expired')], default='Available', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Individual', 'Individual'), ('Gallery', 'Gallery')], max_length=20)),
                ('bio', models.TextField()),
                ('logo', models.ImageField(upload_to='sellers/logos/')),
                ('cover_image', models.ImageField(upload_to='sellers/covers/')),
                ('street_name', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bid_date', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Contingent', 'Contingent')], default='Pending', max_length=20)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='core.artwork')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Finalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('national_id', models.CharField(max_length=50)),
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.bid')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='artwork',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='core.seller'),
        ),
    ]
